WITH TEMP AS (
    SELECT
        REST_ID, 
        ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM
        REST_REVIEW
    GROUP BY
        REST_ID
)
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    T.SCORE
FROM
    REST_INFO I
INNER JOIN TEMP T ON I.REST_ID = T.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
ORDER BY
    T.SCORE DESC,
    I.FAVORITES DESC;
