-- 완료된 중고거래 총 금액이 70만원 이상인 회원 찾기
-- DONE이어야 거래 했다고 포함

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
