-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회한다.
-- 1. 가장 많이 작성한 회원 찾기
-- 2. 그 회원 서브쿼리 기준 리뷰 조회

WITH MOST_REVIEWED AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    FETCH FIRST 1 ROWS ONLY
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT MEMBER_ID FROM MOST_REVIEWED)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT


