-- 코드를 작성해주세요
-- 2022년도 기준 평가점수가 높은 사원 정보 조회
-- 점수 / 사번 / 성명 / 직책 / 이메일


SELECT SUM(GRADE.SCORE) AS SCORE,
       EMP.EMP_NO,
       EMP.EMP_NAME,
       EMP.POSITION,
       EMP.EMAIL
FROM HR_DEPARTMENT AS DEPT
INNER JOIN HR_EMPLOYEES AS EMP ON DEPT.DEPT_ID = EMP.DEPT_ID
INNER JOIN HR_GRADE AS GRADE ON EMP.EMP_NO = GRADE.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC LIMIT 1;