-- 식품 분류 별 / 가격이 제일 비싼 식품 MAX
-- 분류 / 가격 / 이름 
WITH MAX_PRICE AS(
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM MAX_PRICE M JOIN FOOD_PRODUCT F ON M.CATEGORY = F.CATEGORY AND M.MAX_PRICE = F.PRICE
ORDER BY M.MAX_PRICE DESC